### ISSUE TITLE
Doesn't seem to provide any data to Insteon+ app

### ISSUE THREAD

**Issue by Chioti** [rodtoll/homebridge-wireless-sensor-tag#1]
I believe I've installed and configured it correctly, as I see all of my tags in the Insteon+ app.  However it doesn't show any information such as the temperature.  I realize you haven't implemented humidity yet, however I thought the temp should work.  Is there some troubleshooting I should do?

**Comment by rodtoll** [comment]
I don't believe the Insteon+ application supports sensors with temperature. They don't support all types of HomeKit devices.

Could you try a different HomeKit application? i.e. MyTouchHome and see if it works there?

**Comment by Chioti** [comment]
I will try it today.  On a separate note is the fix for ISY available to support more than one scene?

Also, how are you making out with support for IO Linc as a garage door device?

**Comment by Chioti** [comment]
Just tested it with the Elgato Eve app.  Sensors appear and temperature is reported.  Now if only it had the humidity level!

**Comment by rodtoll** [comment]
I'll add the humidity level for my next batch of fixes.

Only one scene supported in homebridge-isy-js is now fixed. Snag the new
version it should be resolved.

I/O linc is also soon on my list. I wanted to get one wired up in my house
so I can test it properly before it gets unleashed on anyone else's garage
door. And I need a way to tell the library to use that device as an I/O
Linc instead of a relay + sensor.

**Comment by Chioti** [comment]
Sounds great.  Would be more than happy to beta the garage door device…

BTW, the multiple scenes works fine.
