### ISSUE TITLE
Feature Request: Humidity Readings

### ISSUE THREAD

**Issue by Chioti** [rodtoll/homebridge-wireless-sensor-tag#4]
Would you be able to add the humidity readings from the tags as well?  HomeKit should support it as my Nests show up with both Temp and Humidity.
Thanks

**Comment by rodtoll** [comment]
I have one of the tags which supports humidity on order. It will be here next week and I'll add humidity support once I have it setup.

**Comment by rodtoll** [comment]
@SteliosMakrinos - Just published v0.0.2 which now supports publishing humidity. Give it a try and let me know if you have any issues.

**Comment by Chioti** [comment]
The tags now all show up with both temperature and humidity, however the humidity reported in 2 different homekit apps is 0%.

**Comment by rodtoll** [comment]
@SteliosMakrinos - 

Oops. This is what happens when you make a last minute change and you don't have unit tests for a project. I put in a protection against the possibility that some of the tags didn't expose humidity (all my tags do though) and reversed the logic.

Just posted a new version to npm. v0.0.3 which fixes the 0 problem. Leaving open until someone confirms this works for someone besides me.

**Comment by Chioti** [comment]
@rodtoll - Works for me now.  All of mine also expose humidity. Thanks for the fix.
